# Generated by Django 5.0.6 on 2024-10-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarlosonCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='Unknown', max_length=512)),
                ('engine_volume', models.CharField(default='Unknown', max_length=128)),
                ('power', models.CharField(default='Unknown', max_length=32)),
                ('year', models.CharField(default='Unknown', max_length=8)),
                ('fuel_type', models.CharField(default='Unknown', max_length=32)),
                ('drive_type', models.CharField(default='Unknown', max_length=32)),
                ('img', models.CharField(default='Unknown', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_code', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('image_path', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_code', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('page_index_path', models.CharField(default='index.html', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RentrideCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='Unknown', max_length=512)),
                ('engine_volume', models.CharField(default='Unknown', max_length=128)),
                ('power', models.CharField(default='Unknown', max_length=32)),
                ('year', models.CharField(default='Unknown', max_length=8)),
                ('fuel_type', models.CharField(default='Unknown', max_length=32)),
                ('drive_type', models.CharField(default='Unknown', max_length=32)),
                ('img', models.CharField(default='Unknown', max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='car',
            name='picture_code',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
