# Generated by Django 5.0.6 on 2024-10-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carlosoncar_image_page_rentridecar_car_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentridecar',
            name='id',
        ),
        migrations.AlterField(
            model_name='rentridecar',
            name='link',
            field=models.CharField(default='Unknown', max_length=512, primary_key=True, serialize=False),
        ),
    ]
