# Generated by Django 5.0.6 on 2024-10-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image_car_created_at_car_name_car_picture_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_code',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
