# Generated by Django 5.0.6 on 2024-10-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_image_id_alter_image_image_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_code', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('page_index_path', models.CharField(default='index.html', max_length=256)),
            ],
        ),
    ]
