# Generated by Django 5.0.6 on 2024-10-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_carlosoncar_id_alter_carlosoncar_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentridecar',
            old_name='drive_type',
            new_name='drive',
        ),
        migrations.RenameField(
            model_name='rentridecar',
            old_name='engine_volume',
            new_name='engine',
        ),
        migrations.RemoveField(
            model_name='rentridecar',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='rentridecar',
            name='img',
        ),
        migrations.RemoveField(
            model_name='rentridecar',
            name='power',
        ),
    ]
