# Generated by Django 5.0.6 on 2024-10-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_drive_type_rentridecar_drive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('detail', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='carlosoncar',
            name='name',
            field=models.CharField(default='Unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='rentridecar',
            name='img',
            field=models.CharField(default='Unknown', max_length=1024),
        ),
        migrations.AddField(
            model_name='rentridecar',
            name='name',
            field=models.CharField(default='Unknown', max_length=1024),
        ),
    ]
