# Generated by Django 5.0.6 on 2024-10-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_react_carlosoncar_name_rentridecar_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentridecar',
            name='price',
            field=models.CharField(default='Unknown', max_length=128),
        ),
    ]
